baseURL = "https://penguin-island.github.io/TENGINEER/"
languageCode = "ja-jp"
title = "学生コミュニティ TENGINEER福岡"
toc = true
hasCJKLanguage = true
enableEmoji = true

[Params]
  copyright = "© 2022 TENGINEER福岡"

[Params.top]
  # Displays top page's item in order.
  # "hero", "activity", "upcoming_event", "past_event", "member", "contact", "twitter" are supported.
  sections = ["hero", "activity", "upcoming_event", "past_event", "twitter"]
  # トップページの活動内容の横に表示する画像の URL
  scenery = ""
